### ISSUE TITLE
ESLint 9 support

### ISSUE THREAD

**Issue by g3r4n** [edvardchen/eslint-plugin-i18next#123]
It seems like the plugin isn't working with the new version of ESLint 9. I got the following error:
```
TypeError: Error while loading rule 'i18next/no-literal-string': Cannot read properties of undefined (reading 'defineTemplateBodyVisitor')
Occurred while linting /Users/enguerrand/projects/modjo-webapp/src/authenticate.service.ts
    at Object.create (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint-plugin-i18next/lib/rules/no-literal-string.js:305:23)
    at createRuleListeners (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:973:21)
    at /Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:1099:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:1031:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:1880:31)
    at Linter._verifyWithFlatConfigArray (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:2016:21)
    at Linter.verify (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:1505:61)
    at Linter.verifyAndFix (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/linter/linter.js:2253:29)
    at verifyText (/Users/enguerrand/projects/modjo-webapp/node_modules/eslint/lib/eslint/eslint.js:496:48)
```
If you guide me, I'm happy to try to help fix it.

**Comment by edvardchen** [comment]
@g3r4n could you share your config?

**Comment by g3r4n** [comment]
all good now !
